name: Landing test CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    if: contains(github.event.head_commit.message, '[test]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PAT }}
      - name: Build
        id: build_push
        run: |
          export IMAGE=${{ env.DOCKER_USER }}/honest-landing-test:$(date +%s)
          docker build . -t ${IMAGE}
          docker push ${IMAGE}
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"

      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose-test.yml
          remote: /honest/landing-test/docker-compose.yml
          concurrency: 20
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            export IMAGE=${{ env.IMAGE }}
            
            cd /honest/landing-test/
            
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d
